MAKERS_AND_MODELS = {
    "Audi": ["A3", "A4", "A6", "Q3", "Q5", "e-tron"],
    "Bentley": ["Continental GT", "Bentayga", "Flying Spur"],
    "BMW": ["1 Series", "3 Series", "5 Series", "X3", "X5", "i3"],
    "Bugatti": ["Veyron", "Chiron", "Divo"],
    "Cadillac": ["ATS", "CTS", "Escalade", "XT5"],
    "Chevrolet": ["Onix", "Cruze", "Camaro", "S10", "Silverado"],
    "Chrysler": ["300", "Pacifica", "Voyager"],
    "Citroën": ["C3", "C4 Cactus", "C5 Aircross"],
    "Dodge": ["Charger", "Challenger", "Durango"],
    "Ferrari": ["F8 Tributo", "812 Superfast", "Roma", "SF90"],
    "Fiat": ["500", "Panda", "Tipo", "Toro", "Argo"],
    "Ford": ["Fiesta", "Focus", "Mustang", "Ranger", "Explorer", "F-150"],
    "Honda": ["Civic", "Accord", "Fit", "HR-V", "CR-V"],
    "Hummer": ["H2", "H3", "Hummer EV"],
    "Hyundai": ["HB20", "Elantra", "Sonata", "Tucson", "Creta", "i30"],
    "Jaguar": ["XE", "XF", "F-Pace", "E-Pace", "F-Type", "I-Pace"],
    "Jeep": ["Renegade", "Compass", "Wrangler", "Grand Cherokee", "Gladiator"],
    "Kia": ["Rio", "Forte", "Soul", "Sportage", "Sorento", "Seltos"],
    "Lamborghini": ["Huracán", "Aventador", "Urus"],
    "Land Rover": ["Defender", "Discovery", "Range Rover Evoque", "Range Rover Sport"],
    "Lexus": ["IS", "ES", "NX", "RX", "UX"],
    "Maserati": ["Ghibli", "Quattroporte", "Levante", "Grecale", "MC20"],
    "McLaren": ["570S", "650S", "720S", "GT", "Artura"],
    "Mercedes-Benz": ["A-Class", "C-Class", "E-Class", "S-Class", "GLA", "GLC", "GLE"],
    "Mini": ["Cooper", "Countryman", "Clubman"],
    "Mitsubishi": ["Lancer", "Outlander", "ASX", "Pajero", "Eclipse Cross"],
    "Nissan": ["March", "Versa", "Sentra", "Kicks", "Qashqai", "Rogue"],
    "Opel": ["Corsa", "Astra", "Insignia", "Mokka"],
    "Peugeot": ["208", "2008", "308", "3008", "5008"],
    "Porsche": ["911", "Cayenne", "Macan", "Panamera", "Taycan", "718"],
    "Renault": ["Clio", "Sandero", "Logan", "Duster", "Captur", "Mégane"],
    "Rolls-Royce": ["Phantom", "Ghost", "Wraith", "Cullinan", "Dawn"],
    "Rover": ["75", "45", "25"],
    "Subaru": ["Impreza", "Legacy", "Forester", "Outback", "XV", "WRX"],
    "Suzuki": ["Swift", "Baleno", "Vitara", "Jimny", "S-Cross"],
    "Tesla": ["Model S", "Model 3", "Model X", "Model Y", "Cybertruck"],
    "Toyota": ["Yaris", "Corolla", "Camry", "Prius", "RAV4", "Hilux"],
    "Volkswagen": ["Polo", "Golf", "Passat", "Tiguan", "T-Cross", "Jetta"],
    "Volvo": ["S60", "S90", "V60", "XC40", "XC60", "XC90"]
}
